/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include <string>
#include <iostream>

void
add_prog_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	char *result_1;
	enum clnt_stat retval_2;
	int_ptr result_2;
	int_ptr sort_1_arg1;
	enum clnt_stat retval_3;
	char *result_3;
	enum clnt_stat retval_4;
	Matrix result_4;
	Matrix matrixmultiply_1_arg1;
	Matrix matrixmultiply_1_arg2;
	enum clnt_stat retval_5;
	char *result_5;
	char *reverseencryptedecho_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADDS_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

  // setup call 1 args & results
  result_1 = (char*) malloc(256);
  
  //setup call 2 args and results
  //sort a list of integers [5,1,3,8]
  //int_ptr_len and int_ptr_val are automatically created by rpcgen for xdr
  //datatype definition of int_ptr<>
  sort_1_arg1.int_ptr_len = 4;
  sort_1_arg1.int_ptr_val = (int*) malloc(sizeof(int)*sort_1_arg1.int_ptr_len);
  sort_1_arg1.int_ptr_val[0] = 5;
  sort_1_arg1.int_ptr_val[1] = 1;
  sort_1_arg1.int_ptr_val[2] = 3;
  sort_1_arg1.int_ptr_val[3] = 8;
  result_2.int_ptr_val = (int*)malloc(sizeof(int)*sort_1_arg1.int_ptr_len);


  //setup call 3 args and results
  result_3 = (char*) malloc(1000);


  //setup call 4 args and results 
  //2x2 matrix w/ another 2x2 matrix. each has values:
  //[5, 1]
  //[3, 8]
  matrixmultiply_1_arg1.matrix = sort_1_arg1;
  matrixmultiply_1_arg1.size1 = 2;
  matrixmultiply_1_arg1.size2 = 2;
  
  matrixmultiply_1_arg2.matrix = sort_1_arg1;
  matrixmultiply_1_arg2.size1 = 2;
  matrixmultiply_1_arg2.size2 = 2;

  result_4.matrix.int_ptr_val = (int*)malloc(sizeof(int)*4);
  
  //setup call 5 args and results 
  std::string s = "Encryption Test";
  reverseencryptedecho_1_arg1 = (char*)malloc(sizeof(s));
  strcpy(reverseencryptedecho_1_arg1, s.c_str()); //copy c++ style string into c style
  result_5 = (char*) malloc(sizeof(s));
  
  // make rpc 
  retval_1 = dateandtime_1(&result_1, clnt);
  if (retval_1 != RPC_SUCCESS) {
	  clnt_perror (clnt, "call failed");
  }
 
  retval_2 = sort_1(sort_1_arg1, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}

	retval_3 = list_1(&result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
  
  retval_4 = matrixmultiply_1(matrixmultiply_1_arg1, matrixmultiply_1_arg2, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
  std::cout << std::endl; 
  std::cout << "Original string: " << reverseencryptedecho_1_arg1 << std::endl;
  retval_5 = reverseencryptedecho_1(reverseencryptedecho_1_arg1, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
  std::cout << "Reversed, Encrypted string: " << result_5 << std::endl; 
  std::cout << std::endl;

  std::cout << "Current Date and Time: " << result_1 << std::endl;
 


  std::cout << "\nSorted list results:" << std::endl; 
  for(int i = 0; i < result_2.int_ptr_len; i++) {
    std::cout << result_2.int_ptr_val[i] << " ";
  } 
  std::cout << std::endl << std::endl;
  std::cout << "Current files in directory:" << std::endl;
  std::cout << result_3;

  std::cout << "\nMatrix Multiply Results:" << std::endl;
  for(int i = 0; i < result_4.matrix.int_ptr_len; i++) {
    std::cout << result_4.matrix.int_ptr_val[i] << " ";
  }
  std::cout << std::endl;
  
  // free memory 
  free(result_1);
  free(sort_1_arg1.int_ptr_val);
  free(result_2.int_ptr_val);
  free(result_3);
  free(result_4.matrix.int_ptr_val);
  free(reverseencryptedecho_1_arg1);
  free(result_5);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	add_prog_1 (host);
exit (0);
}
